/**
 * TypeScript interface emitter.
 *
 * Generates TypeScript interface declarations from parsed C# type definitions.
 * Converts PascalCase property names to camelCase and applies type mapping.
 */

import type { CSharpType } from './csharp-parser.js';

/**
 * Convert a PascalCase name to camelCase.
 *
 * HeadingText → headingText
 * Url → url
 * CSSClass → cssClass
 */
function toCamelCase(name: string): string {
  // Handle leading uppercase run (e.g., CSSClass → cssClass, URL → url)
  let i = 0;
  while (i < name.length && name[i] === name[i]!.toUpperCase() && name[i] !== name[i]!.toLowerCase()) {
    i++;
  }

  if (i === 0) return name;
  if (i === 1) return name[0]!.toLowerCase() + name.slice(1);
  if (i === name.length) return name.toLowerCase();

  // Multiple uppercase letters: lowercase all but the last (which starts the next word)
  return name.slice(0, i - 1).toLowerCase() + name.slice(i - 1);
}

/**
 * Emit the auto-generated file header comment.
 */
export function emitFileHeader(): string {
  return [
    '// ─────────────────────────────────────────────────────────────────────────────',
    '// AUTO-GENERATED by cms-sync — do not edit manually.',
    '// Source: Synergos.CMS C# domain models',
    `// Generated: ${new Date().toISOString().split('T')[0]}`,
    '// ─────────────────────────────────────────────────────────────────────────────',
    '',
  ].join('\n');
}

/**
 * Emit a single TypeScript interface from a parsed C# type.
 *
 * @param type - The parsed C# type definition
 * @param typeMapper - Function to map C# types to TS types
 * @returns TypeScript interface declaration string
 */
export function emitInterface(
  type: CSharpType,
  typeMapper: (t: string) => string,
): string {
  const tsName = stripSuffixes(type.name);
  const lines: string[] = [];

  lines.push(`export interface ${tsName} {`);

  for (const prop of type.properties) {
    const tsType = typeMapper(prop.type);
    const propName = toCamelCase(prop.name);
    const optional = prop.nullable ? '?' : '';
    const defaultComment = prop.defaultValue !== undefined
      ? ` // default: ${JSON.stringify(prop.defaultValue)}`
      : '';

    lines.push(`  readonly ${propName}${optional}: ${tsType};${defaultComment}`);
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Strip known C# suffixes to produce clean TypeScript interface names.
 */
function stripSuffixes(name: string): string {
  return name
    .replace(/ViewModel$/, '')
    .replace(/Model$/, '');
}

/**
 * Emit a barrel export file for the given generated file names.
 *
 * @param fileNames - Array of file names without extension (e.g., ['shared.generated', 'compositions.generated'])
 * @returns TypeScript barrel export string
 */
export function emitBarrelExport(fileNames: string[]): string {
  const lines: string[] = [
    emitFileHeader(),
  ];

  for (const fileName of fileNames) {
    lines.push(`export * from './${fileName}';`);
  }

  lines.push('');

  return lines.join('\n');
}
