// ─── Element Configs: elementSyn* (CDN-hosted, 71) ────────────────────────────
// Source of truth: Synergos.CMS Synergos.CMS.Web/uSync/v9/ContentTypes/elementsyn*.config
// Generated by Ola 53 sync (Synergos.UI ↔ Synergos.CMS).
//
// Each interface mirrors the property aliases of its CMS Element Type.
// Properties from compIntegration / compDom* are intentionally excluded —
// they live in shared base types and are applied by the wrapper, not
// per-component.
//
// Renaming policy: when a CMS property alias changes, this file MUST be
// updated. Do NOT edit by hand without re-syncing against the CMS XMLs.


/** elementSynAccordion — tier:composition → tag:<synergos-accordion> */
export interface AccordionElementConfig {
  readonly itemsJson?: string;
  readonly allowMultiple?: string;
  readonly integration?: string;
}

/** elementSynAudioPlayer — tier:module → tag:<synergos-audio-player> */
export interface AudioPlayerElementConfig {
  readonly audioFile?: string;
  readonly trackTitle?: string;
  readonly artistName?: string;
  readonly integration?: string;
}

/** elementSynAutocomplete — tier:composition → tag:<synergos-autocomplete> */
export interface AutocompleteElementConfig {
  readonly label?: string;
  readonly placeholder?: string;
  readonly suggestionsEndpoint?: string;
  readonly integration?: string;
}

/** elementSynAvatar — tier:primitive → tag:<synergos-avatar> */
export interface AvatarElementConfig {
  readonly avatarImage?: string;
  readonly integration?: string;
}

/** elementSynAvatarGroup — tier:composition → tag:<synergos-avatar-group> */
export interface AvatarGroupElementConfig {
  readonly avatarsJson?: string;
  readonly maxVisible?: string;
  readonly integration?: string;
}

/** elementSynAvatarUpload — tier:composition → tag:<synergos-avatar-upload> */
export interface AvatarUploadElementConfig {
  readonly label?: string;
  readonly uploadEndpoint?: string;
  readonly integration?: string;
}

/** elementSynBadge — tier:primitive → tag:<synergos-badge> */
export interface BadgeElementConfig {
  readonly label?: string;
  readonly integration?: string;
}

/** elementSynBadgeGroup — tier:composition → tag:<synergos-badge-group> */
export interface BadgeGroupElementConfig {
  readonly badgesJson?: string;
  readonly layout?: string;
  readonly integration?: string;
}

/** elementSynBreadcrumb — tier:primitive → tag:<synergos-breadcrumb> */
export interface BreadcrumbElementConfig {
  readonly itemsJson?: string;
  readonly includeStructuredData?: string;
  readonly integration?: string;
}

/** elementSynCalendar — tier:module → tag:<synergos-calendar> */
export interface CalendarElementConfig {
  readonly eventsEndpoint?: string;
  readonly initialMonth?: string;
  readonly integration?: string;
}

/** elementSynCarousel — tier:module → tag:<synergos-carousel> */
export interface CarouselElementConfig {
  readonly slidesJson?: string;
  readonly autoplayInterval?: string;
  readonly integration?: string;
}

/** elementSynChartBar — tier:module → tag:<synergos-chart-bar> */
export interface ChartBarElementConfig {
  readonly chartTitle?: string;
  readonly dataJson?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynCodeBlock — tier:composition → tag:<synergos-code-block> */
export interface CodeBlockElementConfig {
  readonly code?: string;
  readonly language?: string;
  readonly showLineNumbers?: string;
  readonly integration?: string;
}

/** elementSynColorPicker — tier:composition → tag:<synergos-color-picker> */
export interface ColorPickerElementConfig {
  readonly label?: string;
  readonly initialColor?: string;
  readonly paletteJson?: string;
  readonly integration?: string;
}

/** elementSynColorSwatches — tier:composition → tag:<synergos-color-swatches> */
export interface ColorSwatchesElementConfig {
  readonly swatchesJson?: string;
  readonly shape?: string;
  readonly integration?: string;
}

/** elementSynCommentsWidget — tier:module → tag:<synergos-comments-widget> */
export interface CommentsWidgetElementConfig {
  readonly provider?: string;
  readonly threadId?: string;
  readonly configNote?: string;
  readonly integration?: string;
}

/** elementSynCookieConsent — tier:module → tag:<synergos-cookie-consent> */
export interface CookieConsentElementConfig {
  readonly bannerText?: string;
  readonly acceptLabel?: string;
  readonly rejectLabel?: string;
  readonly settingsLabel?: string;
  readonly policyLink?: string;
  readonly integration?: string;
}

/** elementSynCopyButton — tier:primitive → tag:<synergos-copy-button> */
export interface CopyButtonElementConfig {
  readonly copyText?: string;
  readonly buttonLabel?: string;
  readonly feedbackLabel?: string;
  readonly integration?: string;
}

/** elementSynCountdownClock — tier:module → tag:<synergos-countdown-clock> */
export interface CountdownClockElementConfig {
  readonly endDateTime?: string;
  readonly labelFormat?: string;
  readonly integration?: string;
}

/** elementSynCountdownDigital — tier:module → tag:<synergos-countdown-digital> */
export interface CountdownDigitalElementConfig {
  readonly endDateTime?: string;
  readonly showLabels?: string;
  readonly style?: string;
  readonly integration?: string;
}

/** elementSynDataGrid — tier:module → tag:<synergos-data-grid> */
export interface DataGridElementConfig {
  readonly dataSource?: string;
  readonly columnsJson?: string;
  readonly pageSize?: string;
  readonly integration?: string;
}

/** elementSynDatePicker — tier:composition → tag:<synergos-date-picker> */
export interface DatePickerElementConfig {
  readonly label?: string;
  readonly initialDate?: string;
  readonly minDate?: string;
  readonly maxDate?: string;
  readonly integration?: string;
}

/** elementSynDivider — tier:primitive → tag:<synergos-divider> */
export interface DividerElementConfig {
}

/** elementSynDrawer — tier:module → tag:<synergos-drawer> */
export interface DrawerElementConfig {
  readonly triggerLabel?: string;
  readonly drawerContent?: string;
  readonly side?: string;
  readonly integration?: string;
}

/** elementSynDropdown — tier:composition → tag:<synergos-dropdown> */
export interface DropdownElementConfig {
  readonly triggerLabel?: string;
  readonly optionsJson?: string;
  readonly selectedValue?: string;
  readonly searchable?: string;
  readonly integration?: string;
}

/** elementSynDropzone — tier:module → tag:<synergos-dropzone> */
export interface DropzoneElementConfig {
  readonly label?: string;
  readonly acceptedTypes?: string;
  readonly uploadEndpoint?: string;
  readonly integration?: string;
}

/** elementSynFab — tier:primitive → tag:<synergos-fab> */
export interface FabElementConfig {
  readonly iconKey?: string;
  readonly actionLink?: string;
  readonly position?: string;
  readonly integration?: string;
}

/** elementSynFileUploader — tier:module → tag:<synergos-file-uploader> */
export interface FileUploaderElementConfig {
  readonly uploadEndpoint?: string;
  readonly acceptedTypes?: string;
  readonly maxFileSizeMb?: string;
  readonly maxFiles?: string;
  readonly label?: string;
  readonly integration?: string;
}

/** elementSynFormStepper — tier:composition → tag:<synergos-form-stepper> */
export interface FormStepperElementConfig {
  readonly stepsJson?: string;
  readonly submitEndpoint?: string;
  readonly allowSkip?: string;
  readonly integration?: string;
}

/** elementSynHeroBanner — tier:module → tag:<synergos-hero-banner> */
export interface HeroBannerElementConfig {
  readonly title?: string;
  readonly subtitle?: string;
  readonly media?: string;
  readonly ctaLabel?: string;
  readonly ctaLink?: string;
  readonly integration?: string;
}

/** elementSynIconLabel — tier:primitive → tag:<synergos-icon-label> */
export interface IconLabelElementConfig {
  readonly iconKey?: string;
  readonly labelText?: string;
  readonly integration?: string;
}

/** elementSynKpiCard — tier:module → tag:<synergos-kpi-card> */
export interface KpiCardElementConfig {
  readonly kpiLabel?: string;
  readonly kpiValue?: string;
  readonly kpiTrend?: string;
  readonly kpiDelta?: string;
  readonly kpiPeriod?: string;
  readonly integration?: string;
}

/** elementSynLightboxGallery — tier:module → tag:<synergos-lightbox-gallery> */
export interface LightboxGalleryElementConfig {
  readonly imagesJson?: string;
  readonly columns?: string;
  readonly integration?: string;
}

/** elementSynLivestream — tier:module → tag:<synergos-livestream> */
export interface LivestreamElementConfig {
  readonly streamUrl?: string;
  readonly streamType?: string;
  readonly viewerCountEndpoint?: string;
  readonly integration?: string;
}

/** elementSynMapPin — tier:module → tag:<synergos-map-pin> */
export interface MapPinElementConfig {
  readonly centerLat?: string;
  readonly centerLng?: string;
  readonly zoomLevel?: string;
  readonly pinsJson?: string;
  readonly integration?: string;
}

/** elementSynModalTrigger — tier:composition → tag:<synergos-modal-trigger> */
export interface ModalTriggerElementConfig {
  readonly triggerLabel?: string;
  readonly modalTitle?: string;
  readonly modalContent?: string;
  readonly modalSize?: string;
  readonly integration?: string;
}

/** elementSynNotificationCenter — tier:module → tag:<synergos-notification-center> */
export interface NotificationCenterElementConfig {
  readonly fetchEndpoint?: string;
  readonly pollingInterval?: string;
  readonly integration?: string;
}

/** elementSynNotificationToast — tier:module → tag:<synergos-notification-toast> */
export interface NotificationToastElementConfig {
  readonly message?: string;
  readonly type?: string;
  readonly durationMs?: string;
  readonly integration?: string;
}

/** elementSynOEmbed — tier:module → tag:<synergos-oembed> */
export interface OembedElementConfig {
  readonly embedUrl?: string;
  readonly integration?: string;
}

/** elementSynOtpInput — tier:composition → tag:<synergos-otp-input> */
export interface OtpInputElementConfig {
  readonly label?: string;
  readonly length?: string;
  readonly integration?: string;
}

/** elementSynPagination — tier:composition → tag:<synergos-pagination> */
export interface PaginationElementConfig {
  readonly totalItems?: string;
  readonly itemsPerPage?: string;
  readonly currentPage?: string;
  readonly urlTemplate?: string;
  readonly integration?: string;
}

/** elementSynPoll — tier:module → tag:<synergos-poll> */
export interface PollElementConfig {
  readonly question?: string;
  readonly optionsJson?: string;
  readonly voteEndpoint?: string;
  readonly resultsEndpoint?: string;
  readonly integration?: string;
}

/** elementSynPopover — tier:primitive → tag:<synergos-popover> */
export interface PopoverElementConfig {
  readonly triggerLabel?: string;
  readonly popoverContent?: string;
  readonly placement?: string;
  readonly integration?: string;
}

/** elementSynProgressBar — tier:primitive → tag:<synergos-progress-bar> */
export interface ProgressBarElementConfig {
  readonly valueNow?: string;
  readonly valueMax?: string;
  readonly integration?: string;
}

/** elementSynQrCode — tier:primitive → tag:<synergos-qr-code> */
export interface QrCodeElementConfig {
  readonly data?: string;
  readonly size?: string;
  readonly ecLevel?: string;
  readonly integration?: string;
}

/** elementSynQuoteAnimated — tier:module → tag:<synergos-quote-animated> */
export interface QuoteAnimatedElementConfig {
  readonly quote?: string;
  readonly attribution?: string;
  readonly animationMode?: string;
  readonly integration?: string;
}

/** elementSynRangeSlider — tier:composition → tag:<synergos-range-slider> */
export interface RangeSliderElementConfig {
  readonly label?: string;
  readonly minValue?: string;
  readonly maxValue?: string;
  readonly step?: string;
  readonly initialValue?: string;
  readonly integration?: string;
}

/** elementSynRatingStars — tier:composition → tag:<synergos-rating-stars> */
export interface RatingStarsElementConfig {
  readonly valueNow?: string;
  readonly maxStars?: string;
  readonly integration?: string;
}

/** elementSynRichTooltip — tier:composition → tag:<synergos-rich-tooltip> */
export interface RichTooltipElementConfig {
  readonly triggerText?: string;
  readonly tooltipContent?: string;
  readonly placement?: string;
  readonly integration?: string;
}

/** elementSynScrollTop — tier:primitive → tag:<synergos-scroll-top> */
export interface ScrollTopElementConfig {
  readonly scrollThreshold?: string;
  readonly position?: string;
  readonly integration?: string;
}

/** elementSynSearchBox — tier:composition → tag:<synergos-search-box> */
export interface SearchBoxElementConfig {
  readonly searchPlaceholder?: string;
  readonly searchEndpoint?: string;
  readonly searchParamName?: string;
  readonly integration?: string;
}

/** elementSynSelectMulti — tier:composition → tag:<synergos-select-multi> */
export interface SelectMultiElementConfig {
  readonly label?: string;
  readonly optionsJson?: string;
  readonly maxSelections?: string;
  readonly integration?: string;
}

/** elementSynSeparator — tier:primitive → tag:<synergos-separator> */
export interface SeparatorElementConfig {
  readonly style?: string;
  readonly integration?: string;
}

/** elementSynShareBar — tier:composition → tag:<synergos-share-bar> */
export interface ShareBarElementConfig {
  readonly platforms?: string;
  readonly shareLink?: string;
  readonly shareTitle?: string;
  readonly integration?: string;
}

/** elementSynSignaturePad — tier:composition → tag:<synergos-signature-pad> */
export interface SignaturePadElementConfig {
  readonly label?: string;
  readonly width?: string;
  readonly height?: string;
  readonly integration?: string;
}

/** elementSynSkeleton — tier:primitive → tag:<synergos-skeleton> */
export interface SkeletonElementConfig {
  readonly shape?: string;
  readonly count?: string;
  readonly integration?: string;
}

/** elementSynSocialProof — tier:composition → tag:<synergos-social-proof> */
export interface SocialProofElementConfig {
  readonly template?: string;
  readonly dataSource?: string;
  readonly rotationInterval?: string;
  readonly integration?: string;
}

/** elementSynSpacer — tier:primitive → tag:<synergos-spacer> */
export interface SpacerElementConfig {
  readonly size?: string;
  readonly integration?: string;
}

/** elementSynSplitter — tier:composition → tag:<synergos-splitter> */
export interface SplitterElementConfig {
  readonly leftContent?: string;
  readonly rightContent?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynStatTicker — tier:primitive → tag:<synergos-stat-ticker> */
export interface StatTickerElementConfig {
  readonly statValue?: string;
  readonly statLabel?: string;
  readonly statPrefix?: string;
  readonly statSuffix?: string;
  readonly integration?: string;
}

/** elementSynStepper — tier:composition → tag:<synergos-stepper> */
export interface StepperElementConfig {
  readonly stepsJson?: string;
  readonly currentStep?: string;
  readonly integration?: string;
}

/** elementSynTabs — tier:composition → tag:<synergos-tabs> */
export interface TabsElementConfig {
  readonly tabsJson?: string;
  readonly initialTab?: string;
  readonly integration?: string;
}

/** elementSynTag — tier:primitive → tag:<synergos-tag> */
export interface TagElementConfig {
  readonly tagLabel?: string;
  readonly tagColor?: string;
  readonly integration?: string;
}

/** elementSynTestimonialCarousel — tier:module → tag:<synergos-testimonial-carousel> */
export interface TestimonialCarouselElementConfig {
  readonly testimonialsJson?: string;
  readonly autoplayInterval?: string;
  readonly integration?: string;
}

/** elementSynTimeline — tier:module → tag:<synergos-timeline> */
export interface TimelineElementConfig {
  readonly eventsJson?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynTimelineHorizontal — tier:composition → tag:<synergos-timeline-horizontal> */
export interface TimelineHorizontalElementConfig {
  readonly eventsJson?: string;
  readonly snapEnabled?: string;
  readonly integration?: string;
}

/** elementSynToastCenter — tier:module → tag:<synergos-toast-center> */
export interface ToastCenterElementConfig {
  readonly position?: string;
  readonly maxVisible?: string;
  readonly integration?: string;
}

/** elementSynTooltip — tier:primitive → tag:<synergos-tooltip> */
export interface TooltipElementConfig {
  readonly triggerText?: string;
  readonly tooltipText?: string;
  readonly integration?: string;
}

/** elementSynTourGuide — tier:module → tag:<synergos-tour-guide> */
export interface TourGuideElementConfig {
  readonly stepsJson?: string;
  readonly autoStart?: string;
  readonly integration?: string;
}

/** elementSynTreeView — tier:module → tag:<synergos-tree-view> */
export interface TreeViewElementConfig {
  readonly treeJson?: string;
  readonly expandAll?: string;
  readonly integration?: string;
}

/** elementSynVideoPlayer — tier:module → tag:<synergos-video-player> */
export interface VideoPlayerElementConfig {
  readonly videoFile?: string;
  readonly posterImage?: string;
  readonly chaptersJson?: string;
  readonly enableAnalytics?: string;
  readonly integration?: string;
}
