// ─── Element Schemas: elementSyn* (CDN-hosted) ────────────────────────────────
// AUTO-GENERATED by tools/cms-sync.mjs.
// Source of truth: Synergos.CMS Synergos.CMS.Web/uSync/v9/ContentTypes/elementsyn*.config
//
// Each interface mirrors the property aliases of its CMS Element Type 1:1
// (schema-shape). Property names match the CMS uSync XML <Alias> verbatim;
// values are typed as string (CMS serializes everything as text and the
// component does its own type coercion downstream).
//
// Naming convention: `Syn{Pascal}Schema` — distinto del manual
// `element-config.contract.ts` (3-way mirror rich editorial) que usa
// `{Pascal}ElementConfig`. Los dos archivos coexisten sin colisión:
// el rich es el contract canónico para Web Components; el schema mirror
// es para validación / diagnostics / tooling que necesite el shape literal
// del CMS.
//
// To regenerate after CMS changes: `node tools/cms-sync.mjs`.
// Do NOT edit this file by hand.

/** elementSynAcademy — tier:module → tag:<synergos-academy> */
export interface SynAcademySchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynAccordion — tier:composition → tag:<synergos-accordion> */
export interface SynAccordionSchema {
  readonly itemsJson?: string;
  readonly allowMultiple?: string;
  readonly integration?: string;
}

/** elementSynAppLauncher — tier:module → tag:<synergos-app-launcher> */
export interface SynAppLauncherSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apps?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynAudioPlayer — tier:module → tag:<synergos-audio-player> */
export interface SynAudioPlayerSchema {
  readonly audioFile?: string;
  readonly trackTitle?: string;
  readonly artistName?: string;
  readonly integration?: string;
}

/** elementSynAutocomplete — tier:composition → tag:<synergos-autocomplete> */
export interface SynAutocompleteSchema {
  readonly label?: string;
  readonly placeholder?: string;
  readonly suggestionsEndpoint?: string;
  readonly integration?: string;
}

/** elementSynAvatar — tier:primitive → tag:<synergos-avatar> */
export interface SynAvatarSchema {
  readonly avatarImage?: string;
  readonly integration?: string;
}

/** elementSynAvatarGroup — tier:composition → tag:<synergos-avatar-group> */
export interface SynAvatarGroupSchema {
  readonly avatarsJson?: string;
  readonly maxVisible?: string;
  readonly integration?: string;
}

/** elementSynAvatarUpload — tier:composition → tag:<synergos-avatar-upload> */
export interface SynAvatarUploadSchema {
  readonly label?: string;
  readonly uploadEndpoint?: string;
  readonly integration?: string;
}

/** elementSynBadge — tier:primitive → tag:<synergos-badge> */
export interface SynBadgeSchema {
  readonly label?: string;
  readonly integration?: string;
}

/** elementSynBadgeGroup — tier:composition → tag:<synergos-badge-group> */
export interface SynBadgeGroupSchema {
  readonly badgesJson?: string;
  readonly layout?: string;
  readonly integration?: string;
}

/** elementSynBlogs — tier:module → tag:<synergos-blogs> */
export interface SynBlogsSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynBookingWizard — tier:module → tag:<synergos-booking-wizard> */
export interface SynBookingWizardSchema {
  readonly apiBase?: string;
  readonly destinationLabel?: string;
  readonly currency?: string;
  readonly integration?: string;
}

/** elementSynBreadcrumb — tier:primitive → tag:<synergos-breadcrumb> */
export interface SynBreadcrumbSchema {
  readonly itemsJson?: string;
  readonly includeStructuredData?: string;
  readonly integration?: string;
}

/** elementSynCalendar — tier:module → tag:<synergos-calendar> */
export interface SynCalendarSchema {
  readonly eventsEndpoint?: string;
  readonly initialMonth?: string;
  readonly integration?: string;
}

/** elementSynCarousel — tier:module → tag:<synergos-carousel> */
export interface SynCarouselSchema {
  readonly slidesJson?: string;
  readonly autoplayInterval?: string;
  readonly integration?: string;
}

/** elementSynChartBar — tier:module → tag:<synergos-chart-bar> */
export interface SynChartBarSchema {
  readonly chartTitle?: string;
  readonly dataJson?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynCodeBlock — tier:composition → tag:<synergos-code-block> */
export interface SynCodeBlockSchema {
  readonly code?: string;
  readonly language?: string;
  readonly showLineNumbers?: string;
  readonly integration?: string;
}

/** elementSynColorPicker — tier:composition → tag:<synergos-color-picker> */
export interface SynColorPickerSchema {
  readonly label?: string;
  readonly initialColor?: string;
  readonly paletteJson?: string;
  readonly integration?: string;
}

/** elementSynColorSwatches — tier:composition → tag:<synergos-color-swatches> */
export interface SynColorSwatchesSchema {
  readonly swatchesJson?: string;
  readonly shape?: string;
  readonly integration?: string;
}

/** elementSynCommentsWidget — tier:module → tag:<synergos-comments-widget> */
export interface SynCommentsWidgetSchema {
  readonly provider?: string;
  readonly threadId?: string;
  readonly configNote?: string;
  readonly integration?: string;
}

/** elementSynCookieConsent — tier:module → tag:<synergos-cookie-consent> */
export interface SynCookieConsentSchema {
  readonly bannerText?: string;
  readonly acceptLabel?: string;
  readonly rejectLabel?: string;
  readonly settingsLabel?: string;
  readonly policyLink?: string;
  readonly integration?: string;
}

/** elementSynCopyButton — tier:primitive → tag:<synergos-copy-button> */
export interface SynCopyButtonSchema {
  readonly copyText?: string;
  readonly buttonLabel?: string;
  readonly feedbackLabel?: string;
  readonly integration?: string;
}

/** elementSynCountdownClock — tier:module → tag:<synergos-countdown-clock> */
export interface SynCountdownClockSchema {
  readonly endDateTime?: string;
  readonly labelFormat?: string;
  readonly integration?: string;
}

/** elementSynCountdownDigital — tier:module → tag:<synergos-countdown-digital> */
export interface SynCountdownDigitalSchema {
  readonly endDateTime?: string;
  readonly showLabels?: string;
  readonly style?: string;
  readonly integration?: string;
}

/** elementSynDataGrid — tier:module → tag:<synergos-data-grid> */
export interface SynDataGridSchema {
  readonly dataSource?: string;
  readonly columnsJson?: string;
  readonly pageSize?: string;
  readonly integration?: string;
}

/** elementSynDatePicker — tier:composition → tag:<synergos-date-picker> */
export interface SynDatePickerSchema {
  readonly label?: string;
  readonly initialDate?: string;
  readonly minDate?: string;
  readonly maxDate?: string;
  readonly integration?: string;
}

/** elementSynDivider — tier:primitive → tag:<synergos-divider> */
export interface SynDividerSchema {

}

/** elementSynDrawer — tier:module → tag:<synergos-drawer> */
export interface SynDrawerSchema {
  readonly triggerLabel?: string;
  readonly drawerContent?: string;
  readonly side?: string;
  readonly integration?: string;
}

/** elementSynDropdown — tier:composition → tag:<synergos-dropdown> */
export interface SynDropdownSchema {
  readonly triggerLabel?: string;
  readonly optionsJson?: string;
  readonly selectedValue?: string;
  readonly searchable?: string;
  readonly integration?: string;
}

/** elementSynDropzone — tier:module → tag:<synergos-dropzone> */
export interface SynDropzoneSchema {
  readonly label?: string;
  readonly acceptedTypes?: string;
  readonly uploadEndpoint?: string;
  readonly integration?: string;
}

/** elementSynEhr — tier:module → tag:<synergos-ehr> */
export interface SynEhrSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynEventos — tier:module → tag:<synergos-eventos> */
export interface SynEventosSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly role?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynFab — tier:primitive → tag:<synergos-fab> */
export interface SynFabSchema {
  readonly iconKey?: string;
  readonly actionLink?: string;
  readonly position?: string;
  readonly integration?: string;
}

/** elementSynFaqSection — tier:module → tag:<synergos-faq-section> */
export interface SynFaqSectionSchema {
  readonly headingText?: string;
  readonly itemsJson?: string;
  readonly theme?: string;
  readonly integration?: string;
}

/** elementSynFeatureGrid — tier:module → tag:<synergos-feature-grid> */
export interface SynFeatureGridSchema {
  readonly headingText?: string;
  readonly itemsJson?: string;
  readonly columns?: string;
  readonly theme?: string;
  readonly integration?: string;
}

/** elementSynFileUploader — tier:module → tag:<synergos-file-uploader> */
export interface SynFileUploaderSchema {
  readonly uploadEndpoint?: string;
  readonly acceptedTypes?: string;
  readonly maxFileSizeMb?: string;
  readonly maxFiles?: string;
  readonly label?: string;
  readonly integration?: string;
}

/** elementSynFormStepper — tier:composition → tag:<synergos-form-stepper> */
export interface SynFormStepperSchema {
  readonly stepsJson?: string;
  readonly submitEndpoint?: string;
  readonly allowSkip?: string;
  readonly integration?: string;
}

/** elementSynGov — tier:module → tag:<synergos-gov> */
export interface SynGovSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynHeroBanner — tier:module → tag:<synergos-hero-banner> */
export interface SynHeroBannerSchema {
  readonly title?: string;
  readonly subtitle?: string;
  readonly media?: string;
  readonly ctaLabel?: string;
  readonly ctaLink?: string;
  readonly integration?: string;
}

/** elementSynIconLabel — tier:primitive → tag:<synergos-icon-label> */
export interface SynIconLabelSchema {
  readonly iconKey?: string;
  readonly labelText?: string;
  readonly integration?: string;
}

/** elementSynKpiCard — tier:module → tag:<synergos-kpi-card> */
export interface SynKpiCardSchema {
  readonly kpiLabel?: string;
  readonly kpiValue?: string;
  readonly kpiTrend?: string;
  readonly kpiDelta?: string;
  readonly kpiPeriod?: string;
  readonly integration?: string;
}

/** elementSynLightboxGallery — tier:module → tag:<synergos-lightbox-gallery> */
export interface SynLightboxGallerySchema {
  readonly imagesJson?: string;
  readonly columns?: string;
  readonly integration?: string;
}

/** elementSynLivestream — tier:module → tag:<synergos-livestream> */
export interface SynLivestreamSchema {
  readonly streamUrl?: string;
  readonly streamType?: string;
  readonly viewerCountEndpoint?: string;
  readonly integration?: string;
}

/** elementSynMapPin — tier:module → tag:<synergos-map-pin> */
export interface SynMapPinSchema {
  readonly centerLat?: string;
  readonly centerLng?: string;
  readonly zoomLevel?: string;
  readonly pinsJson?: string;
  readonly integration?: string;
}

/** elementSynMediaText — tier:composition → tag:<synergos-media-text> */
export interface SynMediaTextSchema {
  readonly headingText?: string;
  readonly body?: string;
  readonly mediaReference?: string;
  readonly mediaAlt?: string;
  readonly mediaPosition?: string;
  readonly theme?: string;
  readonly integration?: string;
}

/** elementSynModalTrigger — tier:composition → tag:<synergos-modal-trigger> */
export interface SynModalTriggerSchema {
  readonly triggerLabel?: string;
  readonly modalTitle?: string;
  readonly modalContent?: string;
  readonly modalSize?: string;
  readonly integration?: string;
}

/** elementSynModuleMount — tier:module → tag:<synergos-module-mount> */
export interface SynModuleMountSchema {
  readonly moduleAlias?: string;
  readonly moduleInitialRoute?: string;
  readonly moduleHeightHint?: string;
  readonly integration?: string;
}

/** elementSynNotificationCenter — tier:module → tag:<synergos-notification-center> */
export interface SynNotificationCenterSchema {
  readonly fetchEndpoint?: string;
  readonly pollingInterval?: string;
  readonly integration?: string;
}

/** elementSynNotificationToast — tier:module → tag:<synergos-notification-toast> */
export interface SynNotificationToastSchema {
  readonly message?: string;
  readonly type?: string;
  readonly durationMs?: string;
  readonly integration?: string;
}

/** elementSynOEmbed — tier:module → tag:<synergos-oembed> */
export interface SynOembedSchema {
  readonly embedUrl?: string;
  readonly integration?: string;
}

/** elementSynOtpInput — tier:composition → tag:<synergos-otp-input> */
export interface SynOtpInputSchema {
  readonly label?: string;
  readonly length?: string;
  readonly integration?: string;
}

/** elementSynPagination — tier:composition → tag:<synergos-pagination> */
export interface SynPaginationSchema {
  readonly totalItems?: string;
  readonly itemsPerPage?: string;
  readonly currentPage?: string;
  readonly urlTemplate?: string;
  readonly integration?: string;
}

/** elementSynPoll — tier:module → tag:<synergos-poll> */
export interface SynPollSchema {
  readonly question?: string;
  readonly optionsJson?: string;
  readonly voteEndpoint?: string;
  readonly resultsEndpoint?: string;
  readonly integration?: string;
}

/** elementSynPopover — tier:primitive → tag:<synergos-popover> */
export interface SynPopoverSchema {
  readonly triggerLabel?: string;
  readonly popoverContent?: string;
  readonly placement?: string;
  readonly integration?: string;
}

/** elementSynProgressBar — tier:primitive → tag:<synergos-progress-bar> */
export interface SynProgressBarSchema {
  readonly valueNow?: string;
  readonly valueMax?: string;
  readonly integration?: string;
}

/** elementSynQrCode — tier:primitive → tag:<synergos-qr-code> */
export interface SynQrCodeSchema {
  readonly data?: string;
  readonly size?: string;
  readonly ecLevel?: string;
  readonly integration?: string;
}

/** elementSynQuoteAnimated — tier:module → tag:<synergos-quote-animated> */
export interface SynQuoteAnimatedSchema {
  readonly quote?: string;
  readonly attribution?: string;
  readonly animationMode?: string;
  readonly integration?: string;
}

/** elementSynRangeSlider — tier:composition → tag:<synergos-range-slider> */
export interface SynRangeSliderSchema {
  readonly label?: string;
  readonly minValue?: string;
  readonly maxValue?: string;
  readonly step?: string;
  readonly initialValue?: string;
  readonly integration?: string;
}

/** elementSynRatingStars — tier:composition → tag:<synergos-rating-stars> */
export interface SynRatingStarsSchema {
  readonly valueNow?: string;
  readonly maxStars?: string;
  readonly integration?: string;
}

/** elementSynRealty — tier:module → tag:<synergos-realty> */
export interface SynRealtySchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynRichTooltip — tier:composition → tag:<synergos-rich-tooltip> */
export interface SynRichTooltipSchema {
  readonly triggerText?: string;
  readonly tooltipContent?: string;
  readonly placement?: string;
  readonly integration?: string;
}

/** elementSynScrollTop — tier:primitive → tag:<synergos-scroll-top> */
export interface SynScrollTopSchema {
  readonly scrollThreshold?: string;
  readonly position?: string;
  readonly integration?: string;
}

/** elementSynSearchBox — tier:composition → tag:<synergos-search-box> */
export interface SynSearchBoxSchema {
  readonly searchPlaceholder?: string;
  readonly searchEndpoint?: string;
  readonly searchParamName?: string;
  readonly integration?: string;
}

/** elementSynSeatMap — tier:composition → tag:<synergos-seat-map> */
export interface SynSeatMapSchema {
  readonly mapRef?: string;
  readonly maxSelectable?: string;
  readonly currency?: string;
  readonly density?: string;
  readonly hidePrices?: string;
  readonly hideLegend?: string;
  readonly style?: string;
  readonly integration?: string;
}

/** elementSynSelectMulti — tier:composition → tag:<synergos-select-multi> */
export interface SynSelectMultiSchema {
  readonly label?: string;
  readonly optionsJson?: string;
  readonly maxSelections?: string;
  readonly integration?: string;
}

/** elementSynSeller — tier:module → tag:<synergos-seller> */
export interface SynSellerSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynSeparator — tier:primitive → tag:<synergos-separator> */
export interface SynSeparatorSchema {
  readonly style?: string;
  readonly integration?: string;
}

/** elementSynShareBar — tier:composition → tag:<synergos-share-bar> */
export interface SynShareBarSchema {
  readonly platforms?: string;
  readonly shareLink?: string;
  readonly shareTitle?: string;
  readonly integration?: string;
}

/** elementSynSignaturePad — tier:composition → tag:<synergos-signature-pad> */
export interface SynSignaturePadSchema {
  readonly label?: string;
  readonly width?: string;
  readonly height?: string;
  readonly integration?: string;
}

/** elementSynSkeleton — tier:primitive → tag:<synergos-skeleton> */
export interface SynSkeletonSchema {
  readonly shape?: string;
  readonly count?: string;
  readonly integration?: string;
}

/** elementSynSocialProof — tier:composition → tag:<synergos-social-proof> */
export interface SynSocialProofSchema {
  readonly template?: string;
  readonly dataSource?: string;
  readonly rotationInterval?: string;
  readonly integration?: string;
}

/** elementSynSpacer — tier:primitive → tag:<synergos-spacer> */
export interface SynSpacerSchema {
  readonly size?: string;
  readonly integration?: string;
}

/** elementSynSplitter — tier:composition → tag:<synergos-splitter> */
export interface SynSplitterSchema {
  readonly leftContent?: string;
  readonly rightContent?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynStatTicker — tier:primitive → tag:<synergos-stat-ticker> */
export interface SynStatTickerSchema {
  readonly statValue?: string;
  readonly statLabel?: string;
  readonly statPrefix?: string;
  readonly statSuffix?: string;
  readonly integration?: string;
}

/** elementSynStepper — tier:composition → tag:<synergos-stepper> */
export interface SynStepperSchema {
  readonly stepsJson?: string;
  readonly currentStep?: string;
  readonly integration?: string;
}

/** elementSynStorefront — tier:module → tag:<synergos-storefront> */
export interface SynStorefrontSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynTabs — tier:composition → tag:<synergos-tabs> */
export interface SynTabsSchema {
  readonly tabsJson?: string;
  readonly initialTab?: string;
  readonly integration?: string;
}

/** elementSynTag — tier:primitive → tag:<synergos-tag> */
export interface SynTagSchema {
  readonly tagLabel?: string;
  readonly tagColor?: string;
  readonly integration?: string;
}

/** elementSynTestimonialCarousel — tier:module → tag:<synergos-testimonial-carousel> */
export interface SynTestimonialCarouselSchema {
  readonly testimonialsJson?: string;
  readonly autoplayInterval?: string;
  readonly integration?: string;
}

/** elementSynTestimonialSection — tier:module → tag:<synergos-testimonial-section> */
export interface SynTestimonialSectionSchema {
  readonly headingText?: string;
  readonly itemsJson?: string;
  readonly theme?: string;
  readonly integration?: string;
}

/** elementSynTimeline — tier:module → tag:<synergos-timeline> */
export interface SynTimelineSchema {
  readonly eventsJson?: string;
  readonly orientation?: string;
  readonly integration?: string;
}

/** elementSynTimelineHorizontal — tier:composition → tag:<synergos-timeline-horizontal> */
export interface SynTimelineHorizontalSchema {
  readonly eventsJson?: string;
  readonly snapEnabled?: string;
  readonly integration?: string;
}

/** elementSynToastCenter — tier:module → tag:<synergos-toast-center> */
export interface SynToastCenterSchema {
  readonly position?: string;
  readonly maxVisible?: string;
  readonly integration?: string;
}

/** elementSynTooltip — tier:primitive → tag:<synergos-tooltip> */
export interface SynTooltipSchema {
  readonly triggerText?: string;
  readonly tooltipText?: string;
  readonly integration?: string;
}

/** elementSynTourGuide — tier:module → tag:<synergos-tour-guide> */
export interface SynTourGuideSchema {
  readonly stepsJson?: string;
  readonly autoStart?: string;
  readonly integration?: string;
}

/** elementSynTravelShell — tier:module → tag:<synergos-travel-shell> */
export interface SynTravelShellSchema {
  readonly heading?: string;
  readonly subheading?: string;
  readonly apiBase?: string;
  readonly config?: string;
  readonly content?: string;
  readonly integration?: string;
}

/** elementSynTreeView — tier:module → tag:<synergos-tree-view> */
export interface SynTreeViewSchema {
  readonly treeJson?: string;
  readonly expandAll?: string;
  readonly integration?: string;
}

/** elementSynVideoPlayer — tier:module → tag:<synergos-video-player> */
export interface SynVideoPlayerSchema {
  readonly videoFile?: string;
  readonly posterImage?: string;
  readonly chaptersJson?: string;
  readonly enableAnalytics?: string;
  readonly integration?: string;
}
