/**
 * AUTO-GENERATED by tools/cms-sync.mjs.
 * Source: Synergos.CMS Synergos.CMS.Web/uSync/v9/ContentTypes/elementsyn{Name}.config
 * Re-run `node tools/cms-sync.mjs` to regenerate. Edits will be lost.
 */
export interface ShareBarInputs {
  config?: string;
  platforms?: string;
  shareLink?: string;
  shareTitle?: string;
  integration?: string;
}
