/**
 * AUTO-GENERATED by tools/cms-sync.mjs.
 * Source: Synergos.CMS Synergos.CMS.Web/uSync/v9/ContentTypes/elementsyn{Name}.config
 * Re-run `node tools/cms-sync.mjs` to regenerate. Edits will be lost.
 */
export interface SplitterInputs {
  config?: string;
  leftContent?: string;
  rightContent?: string;
  orientation?: string;
  integration?: string;
}
