/**
 * AUTO-GENERATED by tools/cms-sync.mjs.
 * Source: Synergos.CMS Synergos.CMS.Web/uSync/v9/ContentTypes/elementsyn{Name}.config
 * Re-run `node tools/cms-sync.mjs` to regenerate. Edits will be lost.
 */
export interface TestimonialCarouselInputs {
  config?: string;
  testimonialsJson?: string;
  autoplayInterval?: string;
  integration?: string;
}
